apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "capi-flatcar.name" . }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: {{ .Values.cidrBlocks.pods }}
    services:
      cidrBlocks: {{ .Values.cidrBlocks.services }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "capi-flatcar.name" . }}-controller
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: PacketCluster
    name: {{ include "capi-flatcar.name" . }}
