apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ include "capi-flatcar.name" . }}-worker-a
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: ${COREOS_PACKET_HOSTNAME}
          kubeletExtraArgs:
            cloud-provider: external
            volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
      format: ignition
      ignition:
        containerLinuxConfig:
          additionalConfig: |
{{ tpl (.Files.Get "files/ignition.yaml") . | indent 12 }}
      preKubeadmCommands:
        - |
          envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp && mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
          /opt/bootstrap.sh > /opt/bootstrap.log
          export PATH=$PATH:/opt/bin
