{{- $root := . }}
{{- range $worker := .Values.workers }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ include "capi-flatcar.name" $root }}-{{ $worker.prefix }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: ${COREOS_PACKET_HOSTNAME}
          kubeletExtraArgs:
            cloud-provider: external
            volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
      format: ignition
      ignition:
        containerLinuxConfig:
          additionalConfig: |
{{ tpl ($root.Files.Get "files/ignition.yaml") $root | indent 12 }}
      preKubeadmCommands:
        - |
          envsubst < /etc/kubeadm.yml > /etc/kubeadm.yml.tmp && mv /etc/kubeadm.yml.tmp /etc/kubeadm.yml
          /opt/bootstrap.sh > /opt/bootstrap.log
          export PATH=$PATH:/opt/bin

          CCNP_YAML="/opt/default-ccnp.yaml"
          if [ -f ${CCNP_YAML} ]; then
            # apply a default ccnp after cilium is installed
            for i in $(seq 1 3); do
              kubectl get crds ciliumclusterwidenetworkpolicies.cilium.io \
                && kubectl apply -f ${CCNP_YAML} \
                && break \
              || sleep 30
            done
          fi

{{- end }}
