apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: {{ include "capi-flatcar.name" . }}-controller
spec:
  template:
    spec:
      billingCycle: hourly
      # hardwareReservationID: ""
      machineType: {{ .Values.controlplane.machineType }}
      os: {{ .Values.equinixmetal.os }}
      {{ if eq .Values.equinixmetal.os "custom_ipxe" -}}
      ipxeURL: {{ .Values.equinixmetal.ipxeURL }}
      {{ end -}}
      tags: []
