apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: {{ include "capi-flatcar.name" . }}-worker
spec:
  template:
    spec:
      billingCycle: hourly
      # hardwareReservationID: ""
      machineType: {{ .Values.worker.machineType }}
      os: {{ .Values.equinixmetal.os }}
      tags: []
