{{- $root := . }}
{{- range $worker := .Values.workers }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: {{ include "capi-flatcar.name" $root }}-{{ $worker.prefix }}
spec:
  template:
    spec:
      billingCycle: hourly
      # hardwareReservationID: ""
      machineType: {{ $worker.machineType }}
      os: {{ $root.Values.equinixmetal.os }}
      {{ if eq $root.Values.equinixmetal.os "custom_ipxe" -}}
      ipxeURL: {{ $root.Values.equinixmetal.ipxeURL }}
      {{ end -}}
      tags: []
{{- end }}
