---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cilium-crs
spec:
  strategy: "ApplyOnce"
  clusterSelector:
    matchLabels:
      cni: cilium
  resources:
    - kind: ConfigMap
      name: cilium-crs
