nameOverride: "cluster1"

kubeVersion: "v1.28.2"

controlplane:
  count: 1
  machineType: m3.small.x86

# you can specify multiple worker pools with different machine types
workers:
  - prefix: worker-a
    count: 0
    machineType: m3.small.x86

equinixmetal:
  metro: da
  projectID: dc001ab1-9386-4159-b45c-9a1ba0a81611
  os: flatcar_stable

cidrBlocks:
  pods:
    - 192.168.0.0/16
  services:
    - 172.26.0.0/16

ssh:
  adminName: core
  adminPubkeys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGzxTkbVXQR+RRdadSkQ5eKxG53WZTervwMi3GLzlYoO"
  authPrincipals:
    - delivery-infra
  caPub: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGMk7ehnqxvlTWoyhdPJxS+1xYvX/Srq5QMcPQPmjs9M"

versions:
  # https://github.com/kubernetes-sigs/cloud-provider-equinix-metal
  cpem: "v3.6.2"
  # https://github.com/kube-vip/kube-vip
  kubeVip: "v0.6.3"

apiKey: ""
